name: ⚙ dotnet
description: Setup .NET SDK versions

inputs:
  versions:  
    description: 'A JSON file containing an array of versions to install'
    required: true
    default: './.github/workflows/dotnet.json'

runs:
  using: composite
  steps:
    - name: 🤌 dotnet
      if: ${{ !hashFiles(inputs.versions) }}
      uses: devlooped/actions-which-dotnet@main

    - name: 👀 dotnet
      id: dotnet
      shell: bash
      run: |
        # read ${{ inputs.versions }}
        {
          echo 'versions<<EOF'
          echo "$(jq -r '.[]' ${{ inputs.versions }})"
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - name: ⚙ dotnet
      uses: actions/setup-dotnet@v4
      if: steps.dotnet.outputs.versions != ''
      with:
        dotnet-version: ${{ steps.dotnet.outputs.versions }}
