name: runcs
on: 
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to compare to today, ISO format'
        required: false
        default: '2020-03-20'

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: 🏃‍♂️ multiline args
        uses: devlooped/actions-runcs@1
        id: runcs
        with:
          args: |
            simple
            hello world
            it's quoted
            "double quoted"
            single'double"mixed
          script: |
            Console.WriteLine(string.Join(" ", args));

      - name: 👀 output
        run: echo "${{ steps.runcs.outputs.output }}"

      - name: 🏃‍♂️ singleline args
        uses: devlooped/actions-runcs@1
        id: runcsargs
        with:
          args: --arg1 "first arg" --arg2 second
          script: |
            Console.WriteLine(string.Join(" ", args));

      - name: 👀 output
        run: echo "${{ steps.runcsargs.outputs.output }}"

      - name: 🏃‍♂️ c#
        uses: devlooped/actions-runcs@1
        id: runcalc
        with:
          script: |
            #:package Humanizer@2.*
            using Humanizer;

            var date = DateTime.Parse("${{ github.event.inputs.date }}");
            var elapsed = DateTime.Now - date;

            if (elapsed.TotalSeconds > 0)
                Console.WriteLine($"It's been {elapsed.Humanize()} since {date.Humanize()}");
            else
                Console.WriteLine($"Still {elapsed.Negate().Humanize()} until {date.Humanize()}");

      - name: 👀 output
        run: echo "${{ steps.runcalc.outputs.output }}"
