name: runcs
on: 
  workflow_dispatch:
    inputs:
      message:
        description: Message for Hello {message}
        required: true
        default: "World"

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙ runcs
        uses: ./.github/actions/runcs
        id: runcs
        with:
          args: |
            simple
            hello world
            it's quoted
            "double quoted"
            single'double"mixed
          script: |
            Console.WriteLine(string.Join(" ", args));

      - name: 👀 output
        run: echo "${{ steps.runcs.outputs.output }}"